In [1]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
# importing Dataset from Local drive
from google.colab import files
Uploaded=files.upload()

Saving Classification Dataset33.csv to Classification Dataset33.csv


In [3]:
dataset = pd.read_csv('/content/drive/My Drive/ML lab/endterm/Classification Dataset33.csv')

In [4]:
#Print Total number of Rows & columns in dataset
print(dataset.shape)

(564, 9)


In [5]:
#Print Imformation about data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Gender            564 non-null    object 
 1   Glucose           564 non-null    int64  
 2   BP                548 non-null    float64
 3   SkinThickness     553 non-null    float64
 4   Insulin           552 non-null    float64
 5   BMI               547 non-null    float64
 6   PedigreeFunction  546 non-null    float64
 7   Age               564 non-null    int64  
 8   Outcome           564 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 39.8+ KB


In [6]:
print(dataset)

     Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
4      Male      137   NaN           35.0  ...  43.1             2.288   33        1
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             

In [7]:
dataset.isnull().sum()

Gender               0
Glucose              0
BP                  16
SkinThickness       11
Insulin             12
BMI                 17
PedigreeFunction    18
Age                  0
Outcome              0
dtype: int64

In [8]:
dataset = dataset.fillna(method='ffill')

In [9]:
dataset.isnull().sum()

Gender              0
Glucose             0
BP                  0
SkinThickness       0
Insulin             0
BMI                 0
PedigreeFunction    0
Age                 0
Outcome             0
dtype: int64

In [10]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:, 0:8].values
# Extracting dependent variable:
y = dataset.iloc[:, 8].values

In [11]:
print(X)

[['Male' 148 72.0 ... 33.6 0.627 50]
 ['Female' 85 66.0 ... 26.6 0.35100000000000003 31]
 ['Female' 183 64.0 ... 23.3 0.672 32]
 ...
 ['Male' 198 66.0 ... 41.3 0.502 28]
 ['Male' 87 68.0 ... 37.6 0.401 24]
 ['Male' 99 60.0 ... 26.9 0.49700000000000005 32]]


In [12]:
print(y)

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 

In [13]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:,0])


In [14]:
print(X)

[[1 148 72.0 ... 33.6 0.627 50]
 [0 85 66.0 ... 26.6 0.35100000000000003 31]
 [0 183 64.0 ... 23.3 0.672 32]
 ...
 [1 198 66.0 ... 41.3 0.502 28]
 [1 87 68.0 ... 37.6 0.401 24]
 [1 99 60.0 ... 26.9 0.49700000000000005 32]]


In [15]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [16]:
print(X_train)

[[1 119 88.0 ... 45.3 0.507 26]
 [0 106 70.0 ... 39.4 0.605 22]
 [0 111 86.0 ... 30.1 0.14300000000000002 23]
 ...
 [0 196 76.0 ... 35.3 0.875 29]
 [1 159 66.0 ... 30.4 0.38299999999999995 36]
 [1 85 74.0 ... 30.1 0.3 35]]


In [17]:
print(X_test)

[[1 104 76.0 ... 18.4 0.5820000000000001 27]
 [0 99 80.0 ... 19.3 0.284 30]
 [1 109 76.0 ... 27.9 0.64 31]
 ...
 [0 99 74.0 ... 29.0 0.203 32]
 [1 135 94.0 ... 40.6 0.284 26]
 [0 120 70.0 ... 42.9 0.452 30]]


In [18]:
print(y_train)

[0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 1 1 1 0 1
 0 0 1 0 0 0 0 1 1 1 1 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0
 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 1 0 1 1 0 1 1 1 1 0 0 0 1 0 0 1 1 0 1 0
 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 1
 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0
 0 0 1 0 0 0 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 0 0
 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0
 1 1 0 0 0 0 0 1 0 0 1 0 1 1 1 0]


In [19]:
print(y_test)

[0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 0 0 1 0 0 0
 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0]


In [33]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [34]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [35]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [36]:
print(y_pred)

[0 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0
 0 1 1 0 1 1 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0
 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0]


In [37]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[83 12]
 [18 28]]


In [38]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 78.72


In [39]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives)
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.3f' % (precision*100))

Precision: 70.000


In [40]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))

Recall: 60.870


In [41]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# calculate score
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

F-Measure: 65.116


In [42]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/ML lab/endterm/model.pkl', 'wb')) 
# Saving model to disk

[INFO] Saving model...


In [43]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/ML lab/endterm/model.pkl','rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test) 

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0])

In [44]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/ML lab/endterm/naivebayes_model.sav'
joblib.dump(classifier, filename)
 
# some time later...
 
# load the model from disk
randomforest_model = joblib.load(filename)
result = randomforest_model.score(X_test, y_test)
print(result)

0.7872340425531915


In [45]:
Gender =  1#@param {type:"number"}
Glucose =  148#@param {type:"number"}
BP =  73#@param {type:"number"}
SkinThickness =  20#@param {type:"number"}
Insulin =  140#@param {type:"number"}
BMI =  37.4#@param {type:"number"}
PedigreeFunction = 0.191 #@param {type:"number"}
Age =  21#@param {type:"number"}
# load the model from disk
naive_Bayes_model = joblib.load(filename)
     
output=naive_Bayes_model.predict(sc.transform([[Gender, Glucose, BP, SkinThickness, Insulin, BMI, PedigreeFunction, Age]]))
print("Placed =", output)
if output==[1]:
  print('Patient will have disease')
else:
  print('Patient will have not disease')

Placed = [0]
Patient will have not disease


In [46]:
!pip install flask-ngrok

In [48]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [49]:
!pip install streamlit

In [50]:
!pip install pyngrok

In [51]:
!ngrok authtoken 1l8Chfa8ulSrjVty4nEKYRIGimv_434sL7Gi9k1AszUCPjjp1

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [71]:
%%writefile app.py
import streamlit as st 
from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
model = pickle.load(open('/content/drive/My Drive/ML lab/endterm/model.pkl', 'rb')) 
# Feature Scaling
dataset = pd.read_csv('/content/drive/My Drive/ML lab/endterm/Classification Dataset33.csv')
# Extracting independent variable:
X = dataset.iloc[:, 0:8].values
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
def predict_note_authentication(Gender,Glucose,BP,SkinThickness,Insulin,BMI,PedigreeFunction,Age):
  output= model.predict(sc.transform([[Gender,Glucose,BP,SkinThickness,Insulin,BMI,PedigreeFunction,Age]]))
  print("Prediction : ", output)
  if output==[1]:
    prediction=" Patient will have Desease"
  else:
    prediction=" Patient will have not Desease"
  print(prediction)
  return prediction
def main():
    
    html_temp = """
   <div class="" style="background-color:Brown;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:black;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:black;margin-top:10px;">Department of Computer Engineering</p></center> 
   <center><p style="font-size:25px;color:black;margin-top:10px;"Machine Learning Lab Experiment</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    st.header("EndTerm Model Deployment")
    
    #Gender1 = st.select_slider('Select a Gender Male:1 Female:0',options=['1', '0'])
    Gender = st.number_input('Insert Gender Male:1 Female:0')
    Glucose = st.number_input('Insert Glucose level')
    BP = st.number_input('Insert BP level')
    SkinThickness = st.number_input('Insert Skinthickness')
    Insulin = st.number_input('Insert insulin')
    BMI = st.number_input('Insert BMI')
    PedigreeFunction =  st.number_input('Insert PedigreeFunction')
    Age = st.number_input('Insert a Age',12,60)

    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(Gender,Glucose,BP,SkinThickness,Insulin,BMI,PedigreeFunction,Age)
      st.success('Model has predicted {}'.format(result))
      
    if st.button("About"):
      st.subheader("Developed by Pritesh Kumar")
      st.subheader("Student, Department of Computer Engineering")

if __name__=='__main__':
  main()

Overwriting app.py


In [73]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [74]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url

<NgrokTunnel: "http://d32a34b3bf81.ngrok.io" -> "http://localhost:80">

In [75]:
!streamlit run --server.port 80 app.py


  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://35.247.76.249:80

Prediction :  [0]
 Patient will have not Desease
  Stopping...


In [76]:
ngrok.kill()